language: python
python:
  - 2.7
before_install:
 - sudo apt-get -y install python-fuse
install: 
 - pip install rarfile
 - virtualenv /home/vagrant/virtualenv/python$TRAVIS_PYTHON_VERSION --system-site-packages
 - python setup.py install
script:
 - virtualenv /home/vagrant/virtualenv/python$TRAVIS_PYTHON_VERSION --system-site-packages
 - cd t; ./test-read.py
